[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "12.20.0", NODE_ENV = "production", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "12.20.0", NODE_ENV = "production", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"
  NODE_ENV = "development"

[[redirects]]
  from = "http://www.frede.biz/*"
  to = "https://www.frede.io"
  status = 301
  force = true

[[redirects]]
  from = "https://www.frede.biz/*"
  to = "https://www.frede.io"
  status = 301
  force = true

[[redirects]]
  from = "http://frede.biz/*"
  to = "https://www.frede.io"
  status = 301
  force = true

[[redirects]]
  from = "https://frede.biz/*"
  to = "https://www.frede.io"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://res.cloudinary.com https://cloud.typography.com; style-src 'self' https://cloud.typography.com 'unsafe-inline'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; font-src 'self' https://cloud.typography.com data:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"
