[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "12.20.0", NODE_ENV = "production", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "12.20.0", NODE_ENV = "production", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"
  NODE_ENV = "development"

[[redirects]]
  from = "https://www.frede.biz/*"
  to = "https://www.frede.io"
  status = 301

[[redirects]]
  from = "https://frede.biz/*"
  to = "https://www.frede.io"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://res.cloudinary.com https://cloud.typography.com; style-src 'self' 'unsafe-inline';"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
